// <auto-generated />
namespace IBA_Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v3migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201708031431371_v3 migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
