//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_payment_data
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal invoice { get; set; }
        public string process { get; set; }
        public string etrn { get; set; }
        public string returl { get; set; }
        public decimal status { get; set; }
        public string servebase_data { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public string psp_data { get; set; }
        public string wddx_invoice { get; set; }
        public string wddx_invoice_items { get; set; }
        public string retfailureurl { get; set; }
    }
}
