//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_nominal_codes
    {
        public decimal id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public bool payments { get; set; }
        public bool admin_charge { get; set; }
        public bool goodwill { get; set; }
        public bool write_on { get; set; }
        public bool write_off { get; set; }
        public bool remainder { get; set; }
        public bool membership { get; set; }
        public bool conferences { get; set; }
        public bool publications { get; set; }
        public bool merchandise { get; set; }
        public bool library { get; set; }
        public bool other { get; set; }
        public bool general { get; set; }
        public bool active { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string SunOSCode { get; set; }
    }
}
