//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_sage_export
    {
        public decimal id { get; set; }
        public System.Guid administrator { get; set; }
        public decimal number_of_transactions { get; set; }
        public decimal number_of_records { get; set; }
        public decimal total_value { get; set; }
        public bool file_created { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
