//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_proformas
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal record { get; set; }
        public decimal status { get; set; }
        public decimal transaction_type { get; set; }
        public decimal invoice_type { get; set; }
        public decimal currency { get; set; }
        public decimal total_net { get; set; }
        public decimal total_vat { get; set; }
        public decimal gbp_exchange_rate { get; set; }
        public Nullable<decimal> gbp_total_net { get; set; }
        public Nullable<decimal> gbp_total_vat { get; set; }
        public decimal alt_exchange_rate { get; set; }
        public decimal alt_total_net { get; set; }
        public decimal alt_total_vat { get; set; }
        public string vat_number { get; set; }
        public string lawfirm { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string state { get; set; }
        public string pc_zip { get; set; }
        public string country { get; set; }
        public decimal delivery_type { get; set; }
        public System.DateTime membership_year { get; set; }
        public string description { get; set; }
        public decimal exchange_rate { get; set; }
        public decimal alt_total { get; set; }
        public decimal alt_currency { get; set; }
        public Nullable<decimal> invoice { get; set; }
        public System.DateTime date_transaction { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    }
}
