//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_payment_card_types_payment_types
    {
        public decimal id { get; set; }
        public decimal cardtype { get; set; }
        public decimal currency { get; set; }
        public decimal selfservice { get; set; }
        public decimal paymenttype { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
