//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_payment_currency_axis_logons
    {
        public decimal id { get; set; }
        public decimal currency { get; set; }
        public string servebase_axis_emid { get; set; }
        public string servebase_axis_elid { get; set; }
        public string servebase_axis_epww { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
