//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtConferenceIssue
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public int ConferenceID { get; set; }
        public System.Guid ConferenceUid { get; set; }
        public string ConferenceTitle { get; set; }
        public string SubmittedByName { get; set; }
        public string IssueType { get; set; }
        public string Summary { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedBy { get; set; }
        public string TimeReported { get; set; }
        public string Comments { get; set; }
    }
}
