//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtConferenceTicket
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public int ConferenceID { get; set; }
        public int FunctionID { get; set; }
        public int FunctionTypeID { get; set; }
        public string FunctionType { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionTitle { get; set; }
        public System.DateTime FunctionStart { get; set; }
        public string FunctionDay { get; set; }
        public string FunctionStartTime { get; set; }
        public string FunctionLocation { get; set; }
        public int Tickets { get; set; }
        public decimal GBPNet { get; set; }
        public decimal GBPVat { get; set; }
        public decimal USDNet { get; set; }
        public decimal USDVat { get; set; }
        public decimal EURNet { get; set; }
        public decimal EURVat { get; set; }
        public Nullable<decimal> CCYNet { get; set; }
        public Nullable<decimal> CCYVat { get; set; }
        public bool AllowGuests { get; set; }
        public int NominalCodeID { get; set; }
        public string NominalCode { get; set; }
        public bool Published { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedBy { get; set; }
        public bool Hide { get; set; }
        public string FunctionAddress { get; set; }
        public bool SalesClosed { get; set; }
    }
}
