//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtConferenceConfiguration
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public int ConferenceID { get; set; }
        public System.Guid ConferenceUid { get; set; }
        public string ConferenceTitle { get; set; }
        public bool IsActive { get; set; }
        public int EscrowTimeOutMinutes { get; set; }
        public int ConfirmationTimeOut { get; set; }
        public int LiveFeedPageRefresh { get; set; }
        public int LiveFeedScrollCount { get; set; }
        public int LiveFeedScrollTimeout { get; set; }
        public int LiveFeedScrollFade { get; set; }
        public Nullable<int> LocalCurrencyID { get; set; }
        public string LocalCurrencySymbol { get; set; }
        public int GBPCashPaymentTypeID { get; set; }
        public string GBPCashPaymentTypeCode { get; set; }
        public int EURCashPaymentTypeID { get; set; }
        public string EURCashPaymentTypeCode { get; set; }
        public int USDCashPaymentTypeID { get; set; }
        public string USDCashPaymentTypeCode { get; set; }
        public Nullable<int> CCYCashPaymentTypeID { get; set; }
        public string CCYCashPaymentTypeCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedBy { get; set; }
        public int EscrowTimeOutRegistrationMinutes { get; set; }
        public int RegistrationTicketWarningLevel { get; set; }
        public int TimeZoneOffSet { get; set; }
        public bool CCYCCPayments { get; set; }
        public decimal TicketRefundAdminFee { get; set; }
        public int TicketSoldOutCheck { get; set; }
    }
}
