//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CTS_Delegates
    {
        public int ID { get; set; }
        public string UniqueID { get; set; }
        public System.Guid DelegateUid { get; set; }
        public int DelegateID { get; set; }
        public bool IsProcessed { get; set; }
    }
}
