//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CTS_DelegateTicketPayments
    {
        public int ID { get; set; }
        public string UniqueID { get; set; }
        public System.Guid DelegateUid { get; set; }
        public int PaymentTypeID { get; set; }
        public int BankID { get; set; }
        public string STAuthCode { get; set; }
        public string STReference { get; set; }
        public decimal GBPEquivalent { get; set; }
        public decimal ExchangeDiffGBP { get; set; }
        public decimal DifferenceGBP { get; set; }
        public int CurrencyID { get; set; }
        public decimal AmountReceiptCurrency { get; set; }
        public decimal GBPSpotRate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TypeID { get; set; }
        public string PaymentType { get; set; }
        public bool IsProcessed { get; set; }
    }
}
