//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CTS_DelegateTickets
    {
        public int ID { get; set; }
        public string UniqueID { get; set; }
        public System.Guid DelegateUid { get; set; }
        public int DelegateID { get; set; }
        public int RecordID { get; set; }
        public int FunctionID { get; set; }
        public int Tickets { get; set; }
        public int TotalTickets { get; set; }
        public int Complimentary { get; set; }
        public int ComplimentaryTotal { get; set; }
        public bool IsInfoRequest { get; set; }
        public bool IsWaitList { get; set; }
        public decimal Net { get; set; }
        public decimal Vat { get; set; }
        public decimal Total { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public bool IsProcessed { get; set; }
    }
}
