//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_lop_chicago
    {
        public int id { get; set; }
        public Nullable<decimal> @ref { get; set; }
        public string addr1 { get; set; }
        public string forenm { get; set; }
        public string surnm { get; set; }
        public string hotel { get; set; }
        public string country { get; set; }
    }
}
