//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_prague_registration_form
    {
        public decimal iba_number { get; set; }
        public decimal iba_member_number { get; set; }
        public string lawfirm { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public decimal cityid { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public Nullable<decimal> stateid { get; set; }
        public string state { get; set; }
        public decimal countryid { get; set; }
        public string country { get; set; }
        public string pc_zip { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string tel { get; set; }
        public decimal titleid { get; set; }
        public string title { get; set; }
        public string given_name { get; set; }
        public string middle_name { get; set; }
        public string family_name { get; set; }
        public string badge_name { get; set; }
        public Nullable<decimal> suffixid { get; set; }
        public string suffix { get; set; }
        public System.DateTime dob { get; set; }
        public decimal age { get; set; }
        public Nullable<decimal> how_found_iba_id { get; set; }
        public string how_found_iba { get; set; }
        public bool iba_mailings { get; set; }
        public bool thirdparty_mailings { get; set; }
        public string hotel { get; set; }
        public Nullable<decimal> guest1_countryid { get; set; }
        public string guest1_country { get; set; }
        public string guest1_given_name { get; set; }
        public string guest1_middle_name { get; set; }
        public string guest1_family_name { get; set; }
        public Nullable<decimal> guest2_countryid { get; set; }
        public string guest2_country { get; set; }
        public string guest2_given_name { get; set; }
        public string guest2_middle_name { get; set; }
        public string guest2_family_name { get; set; }
        public Nullable<decimal> guest3_countryid { get; set; }
        public string guest3_country { get; set; }
        public string guest3_given_name { get; set; }
        public string guest3_middle_name { get; set; }
        public string guest3_family_name { get; set; }
        public decimal africa_forum { get; set; }
        public decimal euro_forum { get; set; }
        public decimal asia_forum { get; set; }
        public decimal corp_lunch { get; set; }
        public decimal gala_dinner { get; set; }
        public decimal lat_am_forum { get; set; }
        public decimal ppid_lunch { get; set; }
        public decimal lpd_lunch { get; set; }
        public decimal senior_lunch { get; set; }
        public decimal women_lunch { get; set; }
        public decimal guest_count { get; set; }
        public decimal guest_fee { get; set; }
        public decimal registration_fee { get; set; }
        public decimal total_vat { get; set; }
        public decimal total_payable { get; set; }
        public string dietary_requirement_1 { get; set; }
        public string function_1 { get; set; }
        public string date_1 { get; set; }
        public string number_1 { get; set; }
        public string dietary_requirement_2 { get; set; }
        public string function_2 { get; set; }
        public string date_2 { get; set; }
        public string number_2 { get; set; }
        public string dietary_requirement_3 { get; set; }
        public string function_3 { get; set; }
        public string date_3 { get; set; }
        public string number_3 { get; set; }
        public string dietary_requirement_4 { get; set; }
        public string function_4 { get; set; }
        public string date_4 { get; set; }
        public string number_4 { get; set; }
        public bool football { get; set; }
        public bool golf { get; set; }
        public bool speaker { get; set; }
        public string list_of_participants { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<decimal> servebase_epac { get; set; }
        public string servebase_esta { get; set; }
        public string servebase_ecod { get; set; }
        public string servebase_eaut { get; set; }
        public string servebase_eeam_confans { get; set; }
        public string servebase_eeam_authans { get; set; }
        public Nullable<System.DateTime> date_authans { get; set; }
        public Nullable<System.DateTime> date_confans { get; set; }
    }
}
