//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_records
    {
        public C_records()
        {
            this.conf_guest = new HashSet<conf_guest>();
            this.record_sessions = new HashSet<record_sessions>();
        }
    
        public decimal id { get; set; }
        public Nullable<decimal> id2 { get; set; }
        public System.Guid uid { get; set; }
        public decimal parent { get; set; }
        public decimal @class { get; set; }
        public decimal status { get; set; }
        public string status_reason { get; set; }
        public Nullable<decimal> lawyertype { get; set; }
        public Nullable<decimal> membershiptype { get; set; }
        public decimal profession { get; set; }
        public string uli { get; set; }
        public decimal title { get; set; }
        public string given_name { get; set; }
        public string middle_name { get; set; }
        public string family_name { get; set; }
        public string badge_name { get; set; }
        public string badge_title { get; set; }
        public decimal salutation { get; set; }
        public decimal suffix { get; set; }
        public string protech_suffix { get; set; }
        public decimal gender { get; set; }
        public string barassoc_lawsociety { get; set; }
        public decimal lawfirm_title { get; set; }
        public string lawfirm { get; set; }
        public decimal lawfirm_position { get; set; }
        public decimal lawfirm_size { get; set; }
        public string vat_number { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool change_login_details { get; set; }
        public string website { get; set; }
        public System.DateTime dob { get; set; }
        public string dietary_requirements { get; set; }
        public decimal conference_noshow { get; set; }
        public bool iba_mailings { get; set; }
        public bool thirdparty_mailings { get; set; }
        public bool directory_wanted { get; set; }
        public bool enews { get; set; }
        public decimal preferred { get; set; }
        public decimal country { get; set; }
        public decimal conf_country { get; set; }
        public decimal discount { get; set; }
        public decimal how_found_iba { get; set; }
        public Nullable<System.DateTime> date_joined { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> date_left { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public bool internet { get; set; }
        public decimal prospect_reason { get; set; }
        public string comments { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public bool isVatNumberValid { get; set; }
        public string ibaMemberOrganisation { get; set; }
        public Nullable<System.DateTime> ExpectedGraduationDate { get; set; }
        public string ProfileBiography { get; set; }
        public string ProfileImageName { get; set; }
        public bool ProfileMakePublic { get; set; }
        public string ProfileJobTitle { get; set; }
        public bool iba_sponsorship_mailings { get; set; }
        public Nullable<System.DateTime> CommitteeWelcomeEmailLastSentDate { get; set; }
        public string DataOrigin { get; set; }
        public bool IGIWanted { get; set; }
        public bool HasLoggedInBefore { get; set; }
        public bool BLIWanted { get; set; }
        public bool CLIWanted { get; set; }
        public bool COMWanted { get; set; }
        public bool DRIWanted { get; set; }
        public bool IHPWanted { get; set; }
        public bool IRIWanted { get; set; }
        public bool JERLWanted { get; set; }
        public bool HasAllergens { get; set; }
        public string Allergens { get; set; }
    
        public virtual ICollection<conf_guest> conf_guest { get; set; }
        public virtual ICollection<record_sessions> record_sessions { get; set; }
    }
}
