//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_pages
    {
        public decimal page_id { get; set; }
        public string page_name { get; set; }
        public string phys_page_name { get; set; }
        public string page_contents { get; set; }
    }
}
