//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_banners
    {
        public decimal banner_id { get; set; }
        public decimal banner_code { get; set; }
        public string banner_image { get; set; }
        public string banner_link { get; set; }
        public string banner_alt { get; set; }
        public string banner_target { get; set; }
        public bool banner_type { get; set; }
        public decimal banner_rank { get; set; }
        public string banner_path { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
