//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_paper
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal conference_id { get; set; }
        public decimal type_id { get; set; }
        public string title { get; set; }
        public string @abstract { get; set; }
        public string authors { get; set; }
        public string keywords { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public decimal file_size { get; set; }
        public string mime_type { get; set; }
        public Nullable<decimal> fee { get; set; }
        public decimal vat_code_id { get; set; }
        public decimal nominal_code_id { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public bool authorityToSell { get; set; }
    }
}
