//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_fee_structure
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal conference_id { get; set; }
        public string title { get; set; }
        public string code_A { get; set; }
        public decimal type_id { get; set; }
        public Nullable<decimal> early_fee { get; set; }
        public Nullable<decimal> after_early_fee { get; set; }
        public Nullable<decimal> at_conference { get; set; }
        public decimal vat_code_id { get; set; }
        public decimal nominal_code_id { get; set; }
        public bool publish { get; set; }
        public Nullable<decimal> member { get; set; }
        public Nullable<decimal> age { get; set; }
        public Nullable<decimal> lawyer_type_id { get; set; }
        public bool senior_lawyer { get; set; }
        public bool low_gdp_country { get; set; }
        public bool conf_country { get; set; }
        public Nullable<decimal> country_group_id { get; set; }
        public bool guest { get; set; }
        public bool active { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public string code_B { get; set; }
        public bool FreePass { get; set; }
        public string Benefits { get; set; }
        public Nullable<int> DelegateSponsorQuantity { get; set; }
        public Nullable<int> ExhibitorQuantity { get; set; }
        public Nullable<int> free_social_function_id { get; set; }
        public bool SponsorPackage { get; set; }
        public bool ExhibitionPackage { get; set; }
        public Nullable<int> DailyFeeNumberOfDays { get; set; }
        public Nullable<decimal> early_fee_vat { get; set; }
        public Nullable<decimal> after_early_fee_vat { get; set; }
        public Nullable<decimal> at_conference_vat { get; set; }
        public Nullable<decimal> early_fee_gross { get; set; }
        public Nullable<decimal> after_early_fee_gross { get; set; }
        public Nullable<decimal> at_conference_gross { get; set; }
        public Nullable<decimal> lawyer_type_group_id { get; set; }
        public Nullable<decimal> class_id { get; set; }
        public Nullable<int> FreeSocialFunctionQuantity { get; set; }
        public bool Waived { get; set; }
        public bool SessionOnly { get; set; }
        public bool UseForSessionOnlySpeakerReg { get; set; }
    
        public virtual conf_conference conf_conference { get; set; }
        public virtual conf_fee_structure_country_group conf_fee_structure_country_group { get; set; }
        public virtual conf_fee_structure_lawyer_type_group conf_fee_structure_lawyer_type_group { get; set; }
        public virtual mem_class mem_class { get; set; }
    }
}
