//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_website_config
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal conference_id { get; set; }
        public string annual_header_file { get; set; }
        public string annual_css_file { get; set; }
        public string lop_preliminary_file { get; set; }
        public string lop_final_file { get; set; }
        public string accommodation_file { get; set; }
        public string programme_file { get; set; }
        public string DelegateMemberInfoLink { get; set; }
        public string BadgeImage { get; set; }
        public string AlternativePapersLink { get; set; }
        public string spk_chr_reg_form { get; set; }
        public string sponsor_header_file { get; set; }
        public string PATHURL { get; set; }
        public string RSSFeedURL { get; set; }
        public Nullable<int> CacheRSSHours { get; set; }
        public string PATHClientId { get; set; }
        public string PATHClientSecret { get; set; }
        public Nullable<int> PATHEventId { get; set; }
        public string PATHAuthURL { get; set; }
        public string PATHLoginURL { get; set; }
        public string PATHCreateUserURL { get; set; }
        public int DelegateSearchDays { get; set; }
        public bool ShowSlidePresentations { get; set; }
        public bool ShowAudioPresentations { get; set; }
        public bool ShowVideoPresentations { get; set; }
        public bool ShowThumbnailVideoPresentations { get; set; }
        public bool ShowExternalPresentations { get; set; }
    
        public virtual conf_conference conf_conference { get; set; }
    }
}
