//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_function_schedule
    {
        public int id { get; set; }
        public System.Guid uid { get; set; }
        public int conference_id { get; set; }
        public int function_id { get; set; }
        public Nullable<int> estimated_attendees { get; set; }
        public Nullable<int> divisions_headcount { get; set; }
        public Nullable<int> committee_headcount { get; set; }
        public int session_length { get; set; }
        public string preferred_slots { get; set; }
        public string chosen_slot { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public Nullable<int> room_id { get; set; }
        public bool display_location { get; set; }
        public bool av_completed { get; set; }
        public bool roomsetup_completed { get; set; }
        public System.DateTime date_created { get; set; }
        public int administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> administrator_modified { get; set; }
    }
}
