//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_function_av_requirement
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal conference_id { get; set; }
        public decimal function_id { get; set; }
        public decimal av_requirement_id { get; set; }
        public decimal quantity { get; set; }
    
        public virtual conf_av_requirement conf_av_requirement { get; set; }
        public virtual conf_function conf_function { get; set; }
    }
}
