//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_fee_structure_lawyer_type_group_gen_lawyer_types
    {
        public decimal lawyer_type_id { get; set; }
        public decimal lawyer_type_group_id { get; set; }
    
        public virtual conf_fee_structure_lawyer_type_group conf_fee_structure_lawyer_type_group { get; set; }
    }
}
