//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_fee_structure_country_group
    {
        public conf_fee_structure_country_group()
        {
            this.conf_fee_structure = new HashSet<conf_fee_structure>();
            this.conf_fee_structure_country_group_gen_countries = new HashSet<conf_fee_structure_country_group_gen_countries>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    
        public virtual ICollection<conf_fee_structure> conf_fee_structure { get; set; }
        public virtual ICollection<conf_fee_structure_country_group_gen_countries> conf_fee_structure_country_group_gen_countries { get; set; }
    }
}
