//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_wddx_data
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string wddx_conference { get; set; }
        public string wddx_delegate { get; set; }
        public string wddx_functions { get; set; }
        public string wddx_guest { get; set; }
        public Nullable<decimal> delegate_id { get; set; }
        public Nullable<decimal> invoice_id { get; set; }
        public Nullable<decimal> receipt_id { get; set; }
        public bool is_processed { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public string wddx_record { get; set; }
        public string wddx_hotel { get; set; }
        public string wddx_fee { get; set; }
        public int failedAttempts { get; set; }
        public string wddx_spcdelegate { get; set; }
        public string wddx_AtConferenceBasket { get; set; }
    }
}
