//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_delegate_daily_fee_day
    {
        public int id { get; set; }
        public int conference_id { get; set; }
        public int delegate_id { get; set; }
        public int daily_fee_id { get; set; }
        public string daily_fee_type { get; set; }
        public string day_name { get; set; }
        public System.DateTime day_date { get; set; }
    }
}
