//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_delegate_merchandise
    {
        public int delegate_id { get; set; }
        public int merchandise_id { get; set; }
        public int tickets { get; set; }
        public int complimentary { get; set; }
    }
}
