//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_av_requirement
    {
        public conf_av_requirement()
        {
            this.conf_function_av_requirement = new HashSet<conf_function_av_requirement>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
        public bool other { get; set; }
    
        public virtual ICollection<conf_function_av_requirement> conf_function_av_requirement { get; set; }
    }
}
