//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_delegate_output
    {
        public decimal id { get; set; }
        public decimal delegate_id { get; set; }
        public decimal output_id { get; set; }
        public Nullable<System.DateTime> date_printed { get; set; }
        public Nullable<decimal> administrator_printed { get; set; }
    
        public virtual conf_delegate conf_delegate { get; set; }
        public virtual conf_output conf_output { get; set; }
    }
}
