//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_speaker_unit
    {
        public decimal delegate_id { get; set; }
        public decimal unit_id { get; set; }
        public decimal unit_type_id { get; set; }
    
        public virtual conf_delegate conf_delegate { get; set; }
    }
}
