//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_speaker_function
    {
        public decimal delegate_id { get; set; }
        public decimal function_id { get; set; }
        public decimal role_id { get; set; }
        public bool paper_submitted { get; set; }
        public bool abstract_submitted { get; set; }
        public bool biography_submitted { get; set; }
        public bool keywords_submitted { get; set; }
        public bool license_to_publish { get; set; }
        public bool publish { get; set; }
    
        public virtual conf_delegate conf_delegate { get; set; }
        public virtual conf_function conf_function { get; set; }
        public virtual conf_speaker_function_role conf_speaker_function_role { get; set; }
    }
}
