//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_website_content
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
        public string page_name { get; set; }
        public string content { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public decimal order { get; set; }
        public decimal conference_id { get; set; }
    
        public virtual conf_conference conf_conference { get; set; }
    }
}
