//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_schedule_combined_slot
    {
        public int id { get; set; }
        public string combined_slots { get; set; }
        public System.DateTime date_created { get; set; }
        public int administrator_created { get; set; }
    }
}
