//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_delegate_type
    {
        public conf_delegate_type()
        {
            this.conf_delegate = new HashSet<conf_delegate>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
        public string code { get; set; }
        public bool UseInForms { get; set; }
    
        public virtual ICollection<conf_delegate> conf_delegate { get; set; }
    }
}
