//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_delegate_meeting
    {
        public decimal delegate_id { get; set; }
        public decimal function_id { get; set; }
        public decimal tickets { get; set; }
        public decimal complimentary { get; set; }
        public bool wait_list { get; set; }
        public bool info_request { get; set; }
    
        public virtual conf_function conf_function { get; set; }
    }
}
