//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_function_status
    {
        public conf_function_status()
        {
            this.conf_function = new HashSet<conf_function>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<conf_function> conf_function { get; set; }
    }
}
