//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf_hotel
    {
        public conf_hotel()
        {
            this.conf_conference_hotel = new HashSet<conf_conference_hotel>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
        public int hotel_status_id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public decimal city_id { get; set; }
        public string county { get; set; }
        public decimal state_id { get; set; }
        public string pc_zip { get; set; }
        public decimal country_id { get; set; }
        public bool other { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    
        public virtual ICollection<conf_conference_hotel> conf_conference_hotel { get; set; }
    }
}
