//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_committees
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal parent { get; set; }
        public decimal section { get; set; }
        public string description { get; set; }
        public decimal order { get; set; }
        public decimal type { get; set; }
        public Nullable<decimal> currency { get; set; }
        public bool allow_free { get; set; }
        public decimal unit_price { get; set; }
        public decimal unit_price_nonmem { get; set; }
        public Nullable<decimal> vat_code { get; set; }
        public Nullable<decimal> nominal_code { get; set; }
        public bool non_membership { get; set; }
        public bool self_service { get; set; }
        public bool officer_unit { get; set; }
        public bool useInOfficerDirectory { get; set; }
        public bool active { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string websiteLink { get; set; }
        public bool displayOfficer { get; set; }
        public int NumberOfSessions { get; set; }
    
        public virtual gen_sections gen_sections { get; set; }
    }
}
