//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_countries
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public decimal region { get; set; }
        public decimal postal_zone { get; set; }
        public decimal currency { get; set; }
        public string dial_code { get; set; }
        public bool low_gdp { get; set; }
        public bool ec { get; set; }
        public string vat_format { get; set; }
        public decimal charity { get; set; }
        public bool barred { get; set; }
        public Nullable<decimal> postage { get; set; }
        public decimal vat_code_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public bool doNotChargeVatToLocals { get; set; }
        public bool doNotChargeVatToEU { get; set; }
        public bool isUK { get; set; }
        public bool doNotChargeVatToNonEU { get; set; }
        public bool doNotChargeSponsorshipVatToLocals { get; set; }
        public bool doNotChargeSponsorshipVatToEU { get; set; }
        public bool doNotChargeSponsorshipVatToNonEU { get; set; }
        public int OnlinePaymentTypeId { get; set; }
    }
}
