//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_divisions
    {
        public gen_divisions()
        {
            this.gen_sections = new HashSet<gen_sections>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public Nullable<decimal> currency { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<decimal> vat_code { get; set; }
        public Nullable<decimal> nominal_code { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual ICollection<gen_sections> gen_sections { get; set; }
    }
}
