//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_sections
    {
        public gen_sections()
        {
            this.gen_committees = new HashSet<gen_committees>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal division { get; set; }
        public string description { get; set; }
        public bool officer_unit { get; set; }
        public decimal order { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public int NumberOfSessions { get; set; }
    
        public virtual ICollection<gen_committees> gen_committees { get; set; }
        public virtual gen_divisions gen_divisions { get; set; }
    }
}
