//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_addresses
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public decimal city { get; set; }
        public string county { get; set; }
        public decimal state { get; set; }
        public string pc_zip { get; set; }
        public decimal country { get; set; }
        public string protech_extaddress5 { get; set; }
        public string protech_extaddress6 { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public decimal record { get; set; }
        public decimal type { get; set; }
        public bool @default { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public bool PrintName { get; set; }
        public bool PrintLawFirm { get; set; }
        public string alternativeEmail { get; set; }
    }
}
