//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRIActiveContactForm
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<int> HRIContactID { get; set; }
        public string ContactType { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual HRIContact HRIContact { get; set; }
    }
}
