//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRIContactIncoming
    {
        public HRIContactIncoming()
        {
            this.HRIContactCategoryIncomings = new HashSet<HRIContactCategoryIncoming>();
            this.HRIContactLanguageIncomings = new HashSet<HRIContactLanguageIncoming>();
            this.HRIProjectIncomings = new HashSet<HRIProjectIncoming>();
            this.HRITravelInsuranceDetailsIncomings = new HashSet<HRITravelInsuranceDetailsIncoming>();
        }
    
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<int> HRIContactID { get; set; }
        public Nullable<int> IBAMemberID { get; set; }
        public Nullable<bool> ContactIsProcessed { get; set; }
        public string GivenName { get; set; }
        public string MiddleName { get; set; }
        public string FamilyName { get; set; }
        public string Gender { get; set; }
        public string Suffix { get; set; }
        public string Organisation { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string AlternativeEmail { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string CountryDialCode { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string CurriculumVitae { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Title { get; set; }
    
        public virtual HRIContact HRIContact { get; set; }
        public virtual ICollection<HRIContactCategoryIncoming> HRIContactCategoryIncomings { get; set; }
        public virtual ICollection<HRIContactLanguageIncoming> HRIContactLanguageIncomings { get; set; }
        public virtual ICollection<HRIProjectIncoming> HRIProjectIncomings { get; set; }
        public virtual ICollection<HRITravelInsuranceDetailsIncoming> HRITravelInsuranceDetailsIncomings { get; set; }
    }
}
