//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRIProjectIncoming
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public int HRIContactIncomingID { get; set; }
        public string ProjectType { get; set; }
        public string ProjectPosition { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public int Year { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual HRIContactIncoming HRIContactIncoming { get; set; }
    }
}
