//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_class_membership_type_upgrades
    {
        public decimal id { get; set; }
        public decimal class_from { get; set; }
        public decimal class_to { get; set; }
        public decimal membership_type_from { get; set; }
        public decimal membership_type_to { get; set; }
        public bool set_date_joined { get; set; }
        public bool set_expiry_date { get; set; }
        public bool set_date_left { get; set; }
        public decimal default_status { get; set; }
        public bool self_service { get; set; }
        public bool charge_constituents { get; set; }
        public bool charge_committees { get; set; }
        public bool charge_regional_fora { get; set; }
        public bool charge_institutes_trusts { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    }
}
