//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_firm_sizes
    {
        public decimal id { get; set; }
        public int range { get; set; }
        public int drop_down_sequence { get; set; }
        public string description { get; set; }
        public decimal range_from { get; set; }
        public decimal range_to { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
