//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_class_membership_types
    {
        public decimal id { get; set; }
        public decimal @class { get; set; }
        public decimal membership_type { get; set; }
        public bool useDefault { get; set; }
        public string firm_sizes { get; set; }
        public int firm_sizes_range { get; set; }
    }
}
