//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_childrecordimport
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public int ParentClass { get; set; }
        public int ChildClass { get; set; }
        public int ChildMembershipType { get; set; }
        public int ChildProfession { get; set; }
        public int ChildDiscount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
