//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_members_committees
    {
        public decimal id { get; set; }
        public decimal record { get; set; }
        public decimal committee { get; set; }
        public bool free_committee { get; set; }
        public decimal section { get; set; }
        public decimal division { get; set; }
        public decimal committee_type { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
    }
}
