//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_members_notes
    {
        public decimal ID { get; set; }
        public decimal RecordID { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public decimal CreatedByID { get; set; }
        public Nullable<int> NoteTypeID { get; set; }
        public Nullable<int> FollowUpByID { get; set; }
        public Nullable<System.DateTime> FollowUpOn { get; set; }
        public bool IsCompleted { get; set; }
    }
}
