//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class mem_fees_structure
    {
        public decimal id { get; set; }
        public decimal @class { get; set; }
        public decimal membership_type { get; set; }
        public decimal product { get; set; }
        public bool membership_fees_payable { get; set; }
        public bool committee_fees_payable { get; set; }
        public bool institutes_fees_payable { get; set; }
        public bool proforma { get; set; }
        public bool membership_fees_proforma { get; set; }
        public bool committee_fees_proforma { get; set; }
        public bool institutes_fees_proforma { get; set; }
        public bool individual_pricing { get; set; }
        public decimal currency { get; set; }
        public decimal unit_price { get; set; }
        public decimal vatcode_id { get; set; }
        public decimal free_committees_total { get; set; }
        public bool self_service { get; set; }
        public decimal band_from { get; set; }
        public decimal band_to { get; set; }
    }
}
