//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentor
    {
        public int id { get; set; }
        public Nullable<System.Guid> Uid { get; set; }
        public int RecordID { get; set; }
        public int MentoringTypeID { get; set; }
        public string University { get; set; }
        public int YearsAsProfessional { get; set; }
        public string Background { get; set; }
        public string WhyParticipateAsMentor { get; set; }
        public string PreviousExperience { get; set; }
        public string OtherComments { get; set; }
        public string HowDidYouHear { get; set; }
        public bool StudentMentor { get; set; }
        public bool LawFirmMentor { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> CreatedByAdmin { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> ModifiedByAdmin { get; set; }
        public bool Hide { get; set; }
    }
}
