//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorAreasOfPractice
    {
        public int id { get; set; }
        public int RecordID { get; set; }
        public int MentorID { get; set; }
        public int AreaOfPracticeID { get; set; }
    }
}
