//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentoringRelationship
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<int> MentorRecordID { get; set; }
        public Nullable<int> MenteeRecordID { get; set; }
        public Nullable<int> MentorID { get; set; }
        public Nullable<int> MenteeID { get; set; }
        public string MenteeRequestMessage { get; set; }
        public int MentoringStatusID { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
        public string RejectedMotivation { get; set; }
        public bool RejectedMotivationApproved { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> OneMonthEmailSendOn { get; set; }
        public Nullable<System.DateTime> OneMonthEmailSentOn { get; set; }
        public Nullable<System.DateTime> ThreeMonthEmailSendOn { get; set; }
        public Nullable<System.DateTime> ThreeMonthEmailSentOn { get; set; }
        public Nullable<System.DateTime> FiveMonthEmailSendOn { get; set; }
        public Nullable<System.DateTime> FiveMonthEmailSentOn { get; set; }
        public Nullable<System.DateTime> CompletionEmailSendOn { get; set; }
        public Nullable<System.DateTime> CompletionEmailSentOn { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public bool CreatedByAdmin { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ModifiedBy { get; set; }
        public bool ModifiedByAdmin { get; set; }
        public bool Hide { get; set; }
    }
}
