//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileSignInLog
    {
        public int id { get; set; }
        public System.Guid guid { get; set; }
        public int recordId { get; set; }
        public int delegateId { get; set; }
        public int conferenceId { get; set; }
        public string userAgent { get; set; }
        public System.DateTime createdOn { get; set; }
    }
}
