//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetRequest
    {
        public int ID { get; set; }
        public System.Guid Uid { get; set; }
        public int MemberId { get; set; }
        public string MemberEmail { get; set; }
        public bool RequestSentByAdministrator { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime DateRequestExpires { get; set; }
    }
}
