//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_publications
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string cat_no { get; set; }
        public string title { get; set; }
        public decimal type { get; set; }
        public System.DateTime pub_date { get; set; }
        public string isbn { get; set; }
        public string issn { get; set; }
        public decimal pub_size { get; set; }
        public decimal pages { get; set; }
        public decimal format { get; set; }
        public string synopsis { get; set; }
        public bool publish { get; set; }
        public Nullable<decimal> conference { get; set; }
        public decimal fee_member { get; set; }
        public decimal fee_section_committee { get; set; }
        public decimal fee_delegate { get; set; }
        public decimal fee_prospect { get; set; }
        public string vat_code { get; set; }
        public decimal vat_value { get; set; }
        public decimal vat_percentage { get; set; }
        public string cost_code { get; set; }
        public string nominal_code { get; set; }
        public bool stocklevel_use { get; set; }
        public Nullable<decimal> stocklevel_current { get; set; }
        public Nullable<decimal> stocklevel_warning { get; set; }
        public string stocklevel_email { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
