//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_order_items
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal order_id { get; set; }
        public decimal product_id { get; set; }
        public decimal type_id { get; set; }
        public string description { get; set; }
        public decimal invoice_currency { get; set; }
        public decimal quantity { get; set; }
        public decimal unit_price { get; set; }
        public decimal item_net { get; set; }
        public decimal item_vat { get; set; }
        public bool is_postage { get; set; }
        public decimal vat_code { get; set; }
        public decimal vat_percentage { get; set; }
        public string vat_description { get; set; }
        public decimal nominal { get; set; }
        public string nominal_code { get; set; }
        public bool is_paid_for { get; set; }
        public decimal status_id { get; set; }
        public string tracking_reference { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    }
}
