//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_publication
    {
        public pub_publication()
        {
            this.pub_publication_unit = new HashSet<pub_publication_unit>();
        }
    
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal status_id { get; set; }
        public decimal category_id { get; set; }
        public Nullable<decimal> size_id { get; set; }
        public decimal format_id { get; set; }
        public Nullable<decimal> abbreviation_id { get; set; }
        public Nullable<decimal> stock_id { get; set; }
        public decimal currency_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date_published { get; set; }
        public Nullable<decimal> conference { get; set; }
        public bool is_restricted { get; set; }
        public string publisher { get; set; }
        public string co_publisher { get; set; }
        public string isbn_10 { get; set; }
        public string isbn_13 { get; set; }
        public string issn { get; set; }
        public Nullable<int> no_of_pages { get; set; }
        public string @abstract { get; set; }
        public string keywords { get; set; }
        public bool is_myiba { get; set; }
        public string volume { get; set; }
        public string issue { get; set; }
        public Nullable<System.DateTime> cover_date { get; set; }
        public bool is_hard_copy { get; set; }
        public string url_further_details { get; set; }
        public string notes { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public Nullable<decimal> file_size { get; set; }
        public string file_mime_type { get; set; }
        public string image_name { get; set; }
        public string image_type { get; set; }
        public Nullable<decimal> image_size { get; set; }
        public string image_mime_type { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
        public string ContentURL { get; set; }
        public bool IsDonation { get; set; }
    
        public virtual ICollection<pub_publication_unit> pub_publication_unit { get; set; }
    }
}
