//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_merchandise
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal status_id { get; set; }
        public decimal category_id { get; set; }
        public Nullable<decimal> stock_id { get; set; }
        public Nullable<decimal> currency_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string image_name { get; set; }
        public string image_type { get; set; }
        public Nullable<decimal> image_size { get; set; }
        public string image_mime_type { get; set; }
        public bool is_myiba { get; set; }
        public string url_further_details { get; set; }
        public string notes { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    }
}
