//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_publication_unit
    {
        public decimal publication_id { get; set; }
        public decimal unit_id { get; set; }
        public decimal unit_type_id { get; set; }
    
        public virtual pub_publication pub_publication { get; set; }
    }
}
