//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_subscription_purchased
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public Nullable<decimal> order_id { get; set; }
        public decimal quantity { get; set; }
        public decimal subscription_id { get; set; }
        public string record { get; set; }
        public decimal issue_number { get; set; }
        public bool exported { get; set; }
        public Nullable<decimal> exported_count { get; set; }
        public Nullable<System.DateTime> date_exported { get; set; }
        public Nullable<decimal> administrator_exported { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
    }
}
