//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_order_wddx_data
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string wddx_order { get; set; }
        public string wddx_order_items { get; set; }
        public Nullable<decimal> record_id { get; set; }
        public Nullable<decimal> order_id { get; set; }
        public Nullable<decimal> invoice_id { get; set; }
        public Nullable<decimal> receipt_id { get; set; }
        public bool is_processed { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
    }
}
