//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_publication_conference_language
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public decimal publication_conference_id { get; set; }
        public decimal language_id { get; set; }
        public bool is_default { get; set; }
    }
}
