//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_status
    {
        public decimal id { get; set; }
        public System.Guid uid { get; set; }
        public string title { get; set; }
        public bool publications { get; set; }
        public bool merchandise { get; set; }
        public bool subscriptions { get; set; }
        public bool is_active { get; set; }
        public Nullable<decimal> position { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal administrator_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<decimal> administrator_modified { get; set; }
    }
}
