//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBAMembersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZoneInfo
    {
        public int TimeZoneID { get; set; }
        public double OffSet { get; set; }
        public string Display { get; set; }
        public short Bias { get; set; }
        public short StdBias { get; set; }
        public short DltBias { get; set; }
        public short StdMonth { get; set; }
        public short StdDayOfWeek { get; set; }
        public short StdWeek { get; set; }
        public short StdHour { get; set; }
        public short DltMonth { get; set; }
        public short DltDayOfWeek { get; set; }
        public short DltWeek { get; set; }
        public short DltHour { get; set; }
    }
}
